# The Docker image that will be used to build your app
image: python:3.11.6
# Functions that should be executed before the build script is run
before_script:
  - pip install setuptools
pages:
  script:
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
    - done
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH